import { useState } from 'react';

// @/components
import Clock from '@/components/Clock';
import DayBox from '@/components/DayBox';
import Header from '@/components/shared/Header';
import Panel from '@/components/shared/Panel';
import TodoList from '@/components/TodoList';
import AddForm from '@/components/AddForm';

import Head from 'next/head'

import { v4 as uuid } from 'uuid';

const all = ['Sunday', 'Monday', 'Tuesday', 'Wednesday', 'Thursday', 'Friday', 'Saturday']
const labor = ['Monday', 'Tuesday', 'Wednesday', 'Thursday', 'Friday']
const weekend = ['Sunday', 'Saturday']

const days: { [key: string]: string[] } = { all, labor, weekend }

const today = all[new Date().getDay()]

const tasksMock = [
  { id: '1', title: 'task 1', day: 'Sunday' },
  { id: '2', title: 'task 2', day: 'Sunday' },
  { id: '3', title: 'task 3', day: 'Sunday' },
  { id: '4', title: 'task 4', day: 'Sunday' },
  { id: '6', title: 'task 2', day: 'Tuesday' },
  { id: '7', title: 'task 3', day: 'Tuesday' }
]

const tasksMock2 = [
  { id: '1', title: 'task 1', day: 'Sunday' },
  { id: '6', title: 'task 2', day: 'Tuesday' },
  { id: '7', title: 'task 3', day: 'Tuesday' }
]

export default function Home() {
  const [value, setValue] = useState('')
  const [tasks, setTasks] = useState(tasksMock);
  const [selectedDay, setSelectedDay] = useState(today)
  const [displayDays, setDisplayDays] = useState<string>('all')

  const handleChange = (e: any) => {
    setValue(e.target.value);
  }

  const onSubmit = (e: any) => {
    e.preventDefault();
    setTasks([...tasks, { id: uuid(), title: value, day: selectedDay }])
  }

  return (
    <>
      <Head>
        <title>Weekly Planner</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <div className='container mx-auto py-16'>
          <div className='flex justify-between gap-32'>
            <Panel classes={['w-2/3']}>
              <Header />

              <div className='flex justify-between w-1/3'>
                <button className={displayDays === 'weekend' ? 'font-bold' : ''} onClick={() => setDisplayDays('weekend')}>Only weekend</button>
                <button className={displayDays === 'labor' ? 'font-bold' : ''} onClick={() => setDisplayDays('labor')}>Labor days</button>
                <button className={displayDays === 'all' ? 'font-bold' : ''} onClick={() => setDisplayDays('all')}>All days</button>
              </div>

              <div className='grid grid-cols-2 lg:grid-cols-3  xl:grid-cols-4 gap-12 mt-16'>
                {days[displayDays].map((day: string) => (
                  <DayBox
                    key={day}
                    day={day}
                    amountOfTasks={tasks.filter(task => task.day === day).length}
                    onSelect={setSelectedDay}
                    selectedDay={selectedDay}
                  />
                ))}
              </div>

              <div className='mt-16'>
                <p>“We cannot solve problems with the kind of thinking we employed when we came up with them.”</p>
                <span className='font-bold'>— Albert Einstein</span>
              </div>
            </Panel>

            <Panel classes={['w-1/3']}>
              <Clock />

              <h1 className='text-3xl font-bold'>Your Tasks for <span className='text-red-500'>{selectedDay}</span></h1>

              <AddForm
                onSubmit={onSubmit}
                handleChange={handleChange}
                value={value}
              />

              <TodoList tasks={tasks.filter(task => task.day === selectedDay)} />
            </Panel>
          </div>
        </div>
      </main>
    </>
  )
}
